version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    networks:
      - preciousnetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: preciousdb
      POSTGRES_USER: precious
      POSTGRES_PASSWORD: password123
    networks:
      - preciousnetwork

networks:
  preciousnetwork:
    driver: bridge
